# =============================================================================
# Kitty Matugen Template
# =============================================================================

background #11140e
foreground #e1e4d9

cursor #acd28f
cursor_text_color #1a3705

selection_background #3e4a35
selection_foreground #d9e7ca

# ANSI Colors (0-7)
color0 #11140e
color1 #ffb4ab
color2 #acd28f
color3 #a0cfce
color4 #bdcbaf
color5 #304f1a
color6 #1e4e4d
color7 #e1e4d9

# Bright Colors (8-15)
color8 #44483e
color9 #ffb4ab
color10 #acd28f
color11 #a0cfce
color12 #bdcbaf
color13 #304f1a
color14 #1e4e4d
color15 #e1e4d9
