# =============================================================================
# Kitty Matugen Template
# =============================================================================

background #191113
foreground #efdfe1

cursor #ffb1c7
cursor_text_color #551d31

selection_background #5b3f47
selection_foreground #ffd9e2

# ANSI Colors (0-7)
color0 #191113
color1 #ffb4ab
color2 #ffb1c7
color3 #eebd93
color4 #e3bdc6
color5 #703347
color6 #613f1f
color7 #efdfe1

# Bright Colors (8-15)
color8 #514346
color9 #ffb4ab
color10 #ffb1c7
color11 #eebd93
color12 #e3bdc6
color13 #703347
color14 #613f1f
color15 #efdfe1
