# =============================================================================
# Kitty Matugen Template
# =============================================================================

background #1a1111
foreground #f0dede

cursor #ffb3b5
cursor_text_color #561d22

selection_background #5d3f40
selection_foreground #ffdada

# ANSI Colors (0-7)
color0 #1a1111
color1 #ffb4ab
color2 #ffb3b5
color3 #e6c18d
color4 #e6bdbd
color5 #733337
color6 #5c421a
color7 #f0dede

# Bright Colors (8-15)
color8 #524343
color9 #ffb4ab
color10 #ffb3b5
color11 #e6c18d
color12 #e6bdbd
color13 #733337
color14 #5c421a
color15 #f0dede
