# Calidad máxima y hardware acceleration
profile=gpu-hq
hwdec=auto-safe
vo=gpu

# Estética: Sin bordes y centrado
no-border
autofit-larger=90%x90%
cursor-autohide=1000

# Subtítulos elegantes
sub-font='Inter'
sub-font-size=36
sub-color='#FFFFFFFF'
sub-border-size=2
sub-shadow-offset=1
