services:
  linux:
    image: qemux/qemu
    container_name: "${VM_NAME}"
    environment:
      BOOT: "${BOOT:-ubuntu}"
      RAM_SIZE: "${RAM:-4G}"
      CPU_CORES: "${CPUS:-2}"
      DISK_SIZE: "${DISK:-32G}"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "${WEB_PORT:-8006}:8006"
      - "${SSH_PORT:-2222}:22"
    volumes:
      - ./data:/storage
    stop_grace_period: 2m
    restart: on-failure
