services:
  windows:
    image: dockurr/windows
    container_name: "${VM_NAME}"
    environment:
      VERSION: "${WIN_VERSION:-11}"
      RAM_SIZE: "${RAM:-8G}"
      CPU_CORES: "${CPUS:-4}"
      DISK_SIZE: "${DISK:-64G}"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "${WEB_PORT:-8006}:8006"
      - "${RDP_PORT:-3389}:3389/tcp"
      - "${RDP_PORT_UDP:-3389}:3389/udp"
    volumes:
      - ./data:/storage
    stop_grace_period: 2m
    restart: on-failure
