# =============================================================================
# Hyprlock Template (Matugen)
# =============================================================================
# Description : Matugen template for generating Hyprlock configuration.
#               Uses color placeholders that Matugen fills at runtime.
# =============================================================================

general {
    hide_cursor = true
    grace = 5
    no_fade_in = false
}

background {
    monitor =
    path = screenshot
    color = rgba(26, 17, 16, 1)
    blur_passes = 4
    blur_size = 8
    noise = 0.0
    contrast = 1.1
    brightness = 0.6
    vibrancy = 0.15
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(255, 255, 255, 1)
    font_size = 120
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, -30
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%A, %d de %B')"
    color = rgba(255, 255, 255, 1)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 55
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 400, 50
    outline_thickness = 1
    dots_size = 0.25
    dots_spacing = 0.4
    dots_center = true
    outer_color = rgba(255, 180, 168, 1)
    inner_color = rgba(26, 17, 16, 1)
    font_color = rgba(241, 223, 219, 1)
    fade_on_empty = false
    rounding = 0
    check_color = rgba(231, 189, 182, 1)
    fail_color = rgba(255, 180, 171, 1)
    placeholder_text = <i>Enter password... </i>
    hide_input = false
    position = 0, 150
    halign = center
    valign = center
}

# MUSIC
label {
    monitor =
    text = cmd[update:1000] $HOME/.local/bin/zenith-music-show
    color = rgba(255, 255, 255, 1)
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = bottom
}

# BATTERY
label {
    monitor =
    text = cmd[update:30000] $HOME/.local/bin/zenith-battery-capacity
    color = rgba(255, 255, 255, 1)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = -30, 30
    halign = right
    valign = bottom
}
